Added custom macros for redshift predicate workaround
greyscaleai521/grafana pull request #2
Opened 2022-05-27 06:11 UTC by harsha-gsai

Story: #754
Changelog:
- Added Custom macros

2022-05-27 10:35 UTC, gautampunhani requested changes

2022-05-27 10:35 UTC, gautampunhani commented on pkg/tsdb/postgres/macros.go
> +var macrosLogger = log.New("macros")
Can this be a const

2022-05-27 10:35 UTC, gautampunhani commented on pkg/tsdb/postgres/macros.go
>  const rsIdentifier = `([_a-zA-Z0-9]+)`
Can fix the naming convention, can't figure out what rsIdentifier and sExpr is

2022-05-27 10:35 UTC, gautampunhani commented on pkg/tsdb/postgres/macros.go
> +	macrosLogger.Info("evaluating macros", "args", fmt.Sprintf("%v", args))
will this logger inundate the logs? Maybe debug mode

2022-05-27 10:35 UTC, gautampunhani commented on pkg/tsdb/postgres/macros.go
> +	case "__historicQuerySwitch":
since it is public repo, we can refrain from using domain specific names. If I am guessing correctly it is more like a generic switch based on threshold. so "querySwitchBasedOnThreshold"

2022-05-30 05:52 UTC, harsha-gsai commented on pkg/tsdb/postgres/macros.go
>  const rsIdentifier = `([_a-zA-Z0-9]+)`
rsIdentifier and sExpr are part of grafana code

2022-05-30 05:58 UTC, harsha-gsai commented on pkg/tsdb/postgres/macros.go
> +	case "__historicQuerySwitch":
renamed to __isTimeFromOutsideThreshold and _isNull

2022-05-30 06:32 UTC, harsha-gsai commented on pkg/tsdb/postgres/macros.go
> +var macrosLogger = log.New("macros")
tried doing that but as a side effect of .New() function it doesn't let us do that

2022-05-30 06:32 UTC, harsha-gsai commented on pkg/tsdb/postgres/macros.go
> +	macrosLogger.Info("evaluating macros", "args", fmt.Sprintf("%v", args))
changed to Debug mode

2022-06-01 06:14 UTC, merged