Feature 2343 8.3.3
greyscaleai521/grafana pull request #4
Opened 2022-06-07 12:28 UTC by chandra-96

Added Implementation to Show Advanced Filters on show more filters button

2022-06-07 12:41 UTC, gautampunhani requested changes

2022-06-07 12:41 UTC, gautampunhani commented on public/app/features/dashboard/components/SubMenu/SubMenuItems.tsx
> +export const SubMenuItems: FunctionComponent<Props> = ({ variables, filtersExpanded, ExpandFilters }) => {
Can we name this expandfilters as a callback , if it is a callback. e.g. onFilterExpand

2022-06-07 12:41 UTC, gautampunhani commented on public/app/features/dashboard/components/SubMenu/SubMenuItems.tsx
> +  function ChildFilters() {
naming convention of functionss should be consistent

2022-06-07 12:41 UTC, gautampunhani commented on public/app/features/dashboard/components/SubMenu/SubMenuItems.tsx
> +      variable.hide !== VariableHide.hideVariable &&
shouldn't all advanced filters be hidden? I can understand that even this will work, but thought that the other approach could be simpler

2022-06-07 12:48 UTC, chandra-96 commented on public/app/features/dashboard/components/SubMenu/SubMenuItems.tsx
> +      variable.hide !== VariableHide.hideVariable &&
Right now advanced are not named as hidden in Json. So went with this approach

2022-06-08 04:49 UTC, gautampunhani approved these changes

2022-06-08 10:48 UTC, merged